name: Get latest posts from my blog
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/latest-blog-post.yml
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in recent blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          user_agent: "Github-Actions"
          max_post_count: "4"
          feed_list: "https://devopslite.com/feed/"
